# Generated by Django 6.1.1 on 2026-09-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airplanetype",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
