# Generated by Django 6.1.1 on 2026-09-13 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0004_airplane_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="crew",
            options={"ordering": ["first_name", "last_name"]},
        ),
        migrations.AlterModelOptions(
            name="flight",
            options={"ordering": ["arrival_time", "departure_time"]},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="route",
            options={"ordering": ["source__name", "destination__name"]},
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["-order"]},
        ),
    ]
