# Generated by Django 6.1.1 on 2026-09-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0005_alter_crew_options_alter_flight_options_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="airport",
            constraint=models.UniqueConstraint(
                fields=("name", "closest_big_city"), name="unique_airport"
            ),
        ),
    ]
